package com.wha.hbm.model;
// Generated 21 mai 2019 à 10:33:07 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;


import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Conseillers generated by hbm2java
 */
@Entity
@Table(name="conseillers")
  
public class Conseillers  implements java.io.Serializable {


     private Integer consId;
     private String consDateEmbauche;
     private String consNom;
     private String consPrenom;
     private String consEmail;
     private String consTel;
     private String consAdresse;
     private int consCp;
     private String consVille;
   

    public Conseillers() {
    }

	
    public Conseillers(String consDateEmbauche, String consNom, String consPrenom, String consEmail, String consTel, String consAdresse, int consCp, String consVille) {
        this.consDateEmbauche = consDateEmbauche;
        this.consNom = consNom;
        
        this.consPrenom = consPrenom;
        this.consEmail = consEmail;
        this.consTel = consTel;
        this.consAdresse = consAdresse;
        this.consCp = consCp;
        this.consVille = consVille;
    }
   
   
     @Id @GeneratedValue(strategy=GenerationType.AUTO)
    
    @Column(name="cons_id", unique=true, nullable=false)
    public Integer getConsId() {
        return this.consId;
    }
    
    public void setConsId(Integer consId) {
        this.consId = consId;
    }
    
    @Column(name="cons_dateEmbauche", nullable=false, length=10)
    public String getConsDateEmbauche() {
        return this.consDateEmbauche;
    }
    
    public void setConsDateEmbauche(String consDateEmbauche) {
        this.consDateEmbauche = consDateEmbauche;
    }
    
    @Column(name="cons_nom", nullable=false, length=30)
    public String getConsNom() {
        return this.consNom;
    }
    
    public void setConsNom(String consNom) {
        this.consNom = consNom;
    }
    
    @Column(name="cons_prenom", nullable=false, length=30)
    public String getConsPrenom() {
        return this.consPrenom;
    }
    
    public void setConsPrenom(String consPrenom) {
        this.consPrenom = consPrenom;
    }
    
    @Column(name="cons_email", nullable=false, length=50)
    public String getConsEmail() {
        return this.consEmail;
    }
    
    public void setConsEmail(String consEmail) {
        this.consEmail = consEmail;
    }
    
    @Column(name="cons_tel", nullable=false, length=15)
    public String getConsTel() {
        return this.consTel;
    }
    
    public void setConsTel(String consTel) {
        this.consTel = consTel;
    }
    
    @Column(name="cons_adresse", nullable=false)
    public String getConsAdresse() {
        return this.consAdresse;
    }
    
    public void setConsAdresse(String consAdresse) {
        this.consAdresse = consAdresse;
    }
    
    @Column(name="cons_cp", nullable=false)
    public int getConsCp() {
        return this.consCp;
    }
    
    public void setConsCp(int consCp) {
        this.consCp = consCp;
    }
    
    @Column(name="cons_ville", nullable=false, length=30)
    public String getConsVille() {
        return this.consVille;
    }
    
    public void setConsVille(String consVille) {
        this.consVille = consVille;
    }



}


